[build]
  # Next.js uygulamaları için derleme komutu
  command = "npm run build"
  # Next.js'in dağıtım çıktısını belirtir (gereklidir)
  publish = ".next"
  
# Netlify'a bu projenin Next.js olduğunu ve sunucu tarafı mantık gerektiğini belirtmek için gerekli plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Sadece kök adresi (/) ilk varsayılan diliniz olan /tr sayfasına yönlendirir.
[[redirects]]
  from = "/"
  to = "/tr"
  status = 302
  force = true

